### PR TITLE
use azure for everything

### LINKED ISSUE #19: ppc builds for ssl3
#18 didn't work on azure:

https://github.com/conda-forge/cyrus-sasl-feedstock/runs/3880792460

blocks: https://github.com/conda-forge/openldap-feedstock/pull/13

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
  * [ ] hopefully will just fill in the missing `ppc64le` builds and not touch anything else
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes
- fixes #19 (drone and travis are basically not working these days)

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/cyrus-sasl ready for review

**Comment by StephenSmith25** [comment]
Thanks for this @bollwyvl. Would there be an argument that this should bump the build number? Or are we pretty certain that its just going to fill in our missing build (as you say)? Just double checking, but happy to merge otherwise.

**Comment by bollwyvl** [comment]
Sure, a build number can't hurt... will bump...

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Pull request merged**
