### PR TITLE
Patch for osx arm migration

### PR DESCRIPTION
**Pull request by shadowwalkersb**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
@isuruf, missing includes and libraries...

**Comment by shadowwalkersb** [comment]
@conda-forge/core, this is ready for review and merge. Thanks @isuruf for the fix.

**Comment by isuruf** [comment]
@shadowwalkersb, it's not core, you should ping @conda-forge/cyrus-sasl

**Comment by shadowwalkersb** [comment]
> @shadowwalkersb, it's not core, you should ping @conda-forge/cyrus-sasl

...and if they are not available?

**Comment by martindurant** [comment]
I am happy to press the button for you, but I have *no idea* what the patch is - it's been a very long time since I've looked at any of this stuff.

**Comment by shadowwalkersb** [comment]
I just copied @isuruf's suggestion into a new PR as I wasn't able to add it to the bot's PR. After, the initial patch failed, @isuruf fixed it. So, I don't know the technical details myself.

**Comment by shadowwalkersb** [comment]
Should this PR also close #14?

**Comment by martindurant** [comment]
OK, well since it takes the CI from failing to passing, that's good enough for me. @isuruf you are happy?

**Comment by isuruf** [comment]
Since @martindurant don't have objections, merging.

**Comment by martindurant** [comment]
Closes #14

**Comment by shadowwalkersb** [comment]
Thanks!

**Pull request merged**
